[package]
name = "elyld-platform"
description = "Platform traits and IDs for ElyLD"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
derive_more.workspace = true
glob.workspace = true
hashbrown.workspace = true
linker-utils = { path = "../linker-utils", version = "1.0.0" }
object.workspace = true
rayon.workspace = true
elyld-error = { path = "../elyld-error", version = "1.0.0" }
elyld-fs = { path = "../elyld-fs", version = "1.0.0" }
elyld-scripts = { path = "../elyld-scripts", version = "1.0.0" }
elyld-util = { path = "../elyld-util", version = "1.0.0" }
zerocopy.workspace = true

[lints]
workspace = true
