[package]
name = "elyld-util"
description = "Shared utilities for ElyLD"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
bumpalo.workspace = true
derive_more.workspace = true
foldhash.workspace = true
glob.workspace = true
hashbrown.workspace = true
leb128.workspace = true
memchr.workspace = true
object.workspace = true
elyld-error = { path = "../elyld-error", version = "1.0.0" }

[dev-dependencies]
itertools.workspace = true

[lints]
workspace = true
