[package]
name = "libelyld"
description = "A library that provides a fast Linux linker"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
elyld-error = { path = "../elyld-error", version = "1.0.0" }
elyld-fs = { path = "../elyld-fs", version = "1.0.0" }
elyld-platform = { path = "../elyld-platform", version = "1.0.0" }
elyld-args = { path = "../elyld-args", version = "1.0.0" }
elyld-layout = { path = "../elyld-layout", version = "1.0.0" }
elyld-wasm = { path = "../elyld-wasm", version = "1.0.0" }
elyld-macho = { path = "../elyld-macho", version = "1.0.0" }
elyld-elf = { path = "../elyld-elf", version = "1.0.0" }
elyld-scripts = { path = "../elyld-scripts", version = "1.0.0" }
elyld-util = { path = "../elyld-util", version = "1.0.0" }
anyhow.workspace = true
colosseum.workspace = true
crossbeam-queue.workspace = true
crossbeam-utils.workspace = true
foldhash.workspace = true
hashbrown.workspace = true
itertools.workspace = true
memchr.workspace = true
object.workspace = true
perfetto-recorder.workspace = true
rayon.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zerocopy.workspace = true

[target.'cfg(all(target_os = "linux", any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
perf-event.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[features]
default = ["zstd"]

# Support for running the linker as a subprocess.
fork = []

# Support for linker-plugins.
plugins = ["elyld-layout/plugins", "elyld-elf/plugins"]

# Enable support for emitting a perfetto trace.
perfetto = ["perfetto-recorder/enable", "tracing/release_max_level_info"]

# Enable work-in-progress features
wip = []

# Experimental support for linking WebAssembly. Currently incomplete.
wasm = []

# Experimental support for linking Mach-O. Currently incomplete.
macho = []

# Support for zstd compression and decompression of sections.
zstd = ["elyld-elf/zstd"]

[lints]
workspace = true
