[package]
name = "elyld-scripts"
description = "Linker-script, version-script, and export-list parsing for ElyLD"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
derive_more.workspace = true
glob.workspace = true
hashbrown.workspace = true
itertools.workspace = true
object.workspace = true
symbolic-common.workspace = true
symbolic-demangle.workspace = true
tracing.workspace = true
elyld-error = { path = "../elyld-error", version = "1.0.0" }
elyld-util = { path = "../elyld-util", version = "1.0.0" }
winnow.workspace = true

[lints]
workspace = true
