[package]
name = "elyld-fs"
description = "Filesystem and archive I/O for ElyLD"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
libc.workspace = true
memmap2.workspace = true
object.workspace = true
elyld-error = { path = "../elyld-error", version = "1.0.0" }

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
ar.workspace = true

[lints]
workspace = true
