[package]
name = "elyld-args"
description = "Command-line argument parsing for ElyLD"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
derive_more.workspace = true
foldhash.workspace = true
hashbrown.workspace = true
hex.workspace = true
indexmap.workspace = true
itertools.workspace = true
jobserver.workspace = true
object.workspace = true
rayon.workspace = true
strum.workspace = true
tracing.workspace = true
colored.workspace = true
elyld-error = { path = "../elyld-error", version = "1.0.0" }
elyld-fs = { path = "../elyld-fs", version = "1.0.0" }
elyld-platform = { path = "../elyld-platform", version = "1.0.0" }
elyld-scripts = { path = "../elyld-scripts", version = "1.0.0" }
elyld-util = { path = "../elyld-util", version = "1.0.0" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
