[package]
name = "elyld-layout"
description = "Layout, resolution, and symbol-db engine for ElyLD"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
atomic-take.workspace = true
bytesize.workspace = true
colosseum.workspace = true
colored.workspace = true
crossbeam-queue.workspace = true
crossbeam-utils.workspace = true
derive_more.workspace = true
foldhash.workspace = true
hashbrown.workspace = true
itertools.workspace = true
linker-layout = { path = "../linker-layout", version = "1.0.0" }
linker-trace = { path = "../linker-trace", version = "1.0.0" }
linker-utils = { path = "../linker-utils", version = "1.0.0" }
memchr.workspace = true
object.workspace = true
perfetto-recorder.workspace = true
rayon.workspace = true
sharded-offset-map.workspace = true
sharded-vec-writer.workspace = true
smallvec.workspace = true
symbolic-demangle.workspace = true
thread_local.workspace = true
tracing.workspace = true
elyld-args = { path = "../elyld-args", version = "1.0.0" }
elyld-error = { path = "../elyld-error", version = "1.0.0" }
elyld-fs = { path = "../elyld-fs", version = "1.0.0" }
elyld-platform = { path = "../elyld-platform", version = "1.0.0" }
elyld-scripts = { path = "../elyld-scripts", version = "1.0.0" }
elyld-util = { path = "../elyld-util", version = "1.0.0" }
winnow.workspace = true

[dev-dependencies]
tempfile.workspace = true

[features]
plugins = []

[lints]
workspace = true
