[package]
name = "elyld-elf"
description = "ELF linking support for ElyLD"
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
crossbeam-utils.workspace = true
derive_more.workspace = true
flate2.workspace = true
foldhash.workspace = true
gimli.workspace = true
hashbrown.workspace = true
indexmap.workspace = true
itertools.workspace = true
leb128.workspace = true
libc.workspace = true
libloading = { workspace = true, optional = true }
linker-utils = { path = "../linker-utils", version = "1.0.0" }
memchr.workspace = true
object = { workspace = true, features = ["write_std"] }
perfetto-recorder.workspace = true
rayon.workspace = true
smallvec.workspace = true
tracing.workspace = true
uuid.workspace = true
elyld-args = { path = "../elyld-args", version = "1.0.0" }
elyld-error = { path = "../elyld-error", version = "1.0.0" }
elyld-fs = { path = "../elyld-fs", version = "1.0.0" }
elyld-layout = { path = "../elyld-layout", version = "1.0.0" }
elyld-platform = { path = "../elyld-platform", version = "1.0.0" }
elyld-scripts = { path = "../elyld-scripts", version = "1.0.0" }
elyld-util = { path = "../elyld-util", version = "1.0.0" }
zerocopy.workspace = true
zlib-rs.workspace = true
zstd = { workspace = true, optional = true }

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[build-dependencies]
cc.workspace = true

[features]
plugins = ["libloading", "elyld-layout/plugins"]
zstd = ["dep:zstd"]

[lints]
workspace = true
